---
- hosts: webservers
  become: yes
  gather_facts: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Python3 and Gunicorn
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - gunicorn

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Copy the Flask application code
      copy:
        src: ./app.py
        dest: /home/ubuntu/app.py
        owner: ubuntu
        mode: '0644'

    - name: Run Flask application using Gunicorn
      shell: gunicorn -w 2 -D -b 0.0.0.0:5000 app:app

- hosts: proxy
  become: yes
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        validate: 'haproxy -c -f %s'
      notify: restart haproxy

    - name: Ensure HAProxy is enabled and started
      service:
        name: haproxy
        state: started
        enabled: yes

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
